name: Manage issues
on:
    issues:
        types: [opened]
    workflow_dispatch:
jobs:
    read-issue:
        runs-on: ubuntu-latest
        steps:
            - name: print context
              run: echo ${{ toJSON(github)}}